### PR TITLE
Restore this.path when upstream

### PR DESCRIPTION
**Pull request by nswbmw**
keep compatibility.

### CODE REVIEW

**Comment by tj** [comment]
weird I swear we did this recently, maybe it was another module. mind adding a test?

**Comment by tejasmanohar** [comment]
thoughts? i'm :+1: since it's pretty much a bug fix and @nswbmw added tests.

**Comment by tj** [comment]
missed that thanks for the ping!

**Comment by tj** [comment]
1.1.1

**Pull request merged**
