### PR TITLE
support rewriting to querystring

### PR DESCRIPTION
**Pull request by 75lb**
this performs the rewrite on `ctx.url` (which includes the querystring) rather than `ctx.path` which does not.

### CODE REVIEW

**Comment by coderhaoxin** [comment]
#8 , cc @tj

**Comment by tejasmanohar** [comment]
:+1: I dig it. [express-rewrite](https://github.com/joehewitt/express-rewrite) supports this as well.

**Comment by thecotne** [comment]
any progress on this?

**Comment by coderhaoxin** [comment]
why this PR includes `v2 commits`?

**Comment by 75lb** [comment]
because it's branched off v2 (next)

**Comment by tejasmanohar** [comment]
then, it should be pr'd to `next` :P

**Comment by 75lb** [comment]
yeah, true :)

see the [new PR](https://github.com/koajs/rewrite/pull/13)

**Pull request closed without merging**
